services:
  ros2:
    build: .
    container_name: ros2_image_processor
    volumes:
      - ./src:/ros2_ws/src
      - ./output:/ros2_ws/output
      - /dev:/dev
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
